### ISSUE TITLE
ESM support (hybird module)

### ISSUE THREAD

**Issue by theoparis** [ShadiestGoat/mongosteel#1]
**Is your feature request related to a problem? Please describe.**

I could use this in ESM however importing seems to be a pain. You could make this a hybrid npm package that outputs both ESM and commonjs.

One way to do this would be to have two tsconfig files, one for esm and one for commonjs, and have them output to their own build directory.  I think then you just need to add a module or exports field to the package.json.

**Comment by ShadiestGoat** [comment]
As of 1.3.3 (.2, .1 & .0 have a lot of issues, since I'm dumb) both esm and cjs is supported ^^
